-- Table: public.Veiculos

-- DROP TABLE IF EXISTS public."Veiculos";

CREATE TABLE IF NOT EXISTS public."Veiculos"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Chassi" text COLLATE pg_catalog."default" NOT NULL,
    "TipoVeiculo" integer NOT NULL,
    "Cor" text COLLATE pg_catalog."default" NOT NULL,
    "Latitude" double precision NOT NULL DEFAULT 0.0,
    "Longitude" double precision NOT NULL DEFAULT 0.0,
    "Placa" text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
    "ImageUrl" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Veiculos" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Veiculos"
    OWNER to postgres;
-- Index: IX_Veiculos_Chassi

-- DROP INDEX IF EXISTS public."IX_Veiculos_Chassi";

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Veiculos_Chassi"
    ON public."Veiculos" USING btree
    ("Chassi" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: IX_Veiculos_Placa

-- DROP INDEX IF EXISTS public."IX_Veiculos_Placa";

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Veiculos_Placa"
    ON public."Veiculos" USING btree
    ("Placa" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;